Repository bcgov/biohubbc, pull requests merged in 2021-03, with the labels that each got.

#95 Project POST endpoint to accept geometry collection
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  database/src/migrations/20210107132219_setup_biohub_db.ts
  database/src/migrations/20210224144754_alter_project_table.ts
  env_config/env.docker
  testing/integration/postman/BioHubBC-API-DEV.postman_collection.json
Labels: db, enhancement

#100 779/875: Location Shapefile Upload onto Map
  app/package.json
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/features/projects/components/ProjectLocationForm.test.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/utils/MapEditControls.tsx
Labels: enhancement, frontend

#102 Add comment
  app/src/features/projects/components/ProjectLocationForm.tsx
Labels: documentation

#103 867: Objectives section to create project form
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectObjectivesForm.test.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectObjectivesForm.test.tsx.snap
  app/src/interfaces/useBioHubApi-interfaces.ts
Labels: enhancement, forms, frontend

#104 Form placeholder cleanup/shrink
  app/src/components/fields/AutocompleteField.tsx
  app/src/components/fields/MultiAutocompleteFieldVariableSize.tsx
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectCoordinatorForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectObjectivesForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectSpeciesForm.test.tsx.snap
Labels: enhancement, forms, frontend

#106 Create Project UI Updates
  app/package-lock.json
  app/package.json
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectCoordinatorForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/styles.scss
  app/src/themes/appTheme.ts
Labels: enhancement

#110 868 Frontend: IUCN Classifications
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/ProjectIUCNForm.test.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
Labels: enhancement, frontend

#111 Minor updates to UI and styling/static deployment
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
  app/src/themes/appTheme.ts
  database/.pipeline/config.js
Labels: enhancement, frontend

#113 Test coverage improvements (part 1 of many)
  app/src/components/dialog/ErrorDialog.test.tsx
  app/src/components/dialog/__snapshots__/ErrorDialog.test.tsx.snap
  app/src/components/fields/MultiAutocompleteField.test.tsx
  app/src/components/fields/__snapshots__/MultiAutocompleteField.test.tsx.snap
  app/src/features/projects/ProjectsLayout.test.tsx
  app/src/features/projects/ProjectsLayout.tsx
  app/src/features/projects/__snapshots__/ProjectsLayout.test.tsx.snap
Labels: technical debt

#114 Add the jira-lint file
  .github/workflows/jira-lint.yml
Labels: BioHubBC, Task

#117 BHBC-865
  api/src/models/permit-no-sampling.test.ts
  api/src/models/permit-no-sampling.ts
  api/src/openapi/schemas/permit-no-sampling.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/permit-no-sampling.ts
  api/src/paths/project.ts
  api/src/paths/projects/{projectId}/artifacts/upload.test.ts
  api/src/queries/permit-no-sampling-queries.test.ts
  api/src/queries/permit-no-sampling-queries.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectPermitForm.test.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useBioHubApi-interfaces.ts
  testing/integration/postman/BioHubBC-API-DEV.postman_collection.json
Labels: BioHubBC, Story

#122 Implement the IUCN section of the "Create Project" form
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/codes.ts
  api/src/paths/project.ts
  api/src/queries/code-queries.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  api/src/utils/code-utils.ts
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectIUCNForm.test.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
  app/src/interfaces/useBioHubApi-interfaces.ts
Labels: BioHubBC, Story, Task, enhancement

#123 875: Map boundary and project structure
  api/src/models/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/paths/projects.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/ProjectSurveys.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/project-interfaces.ts
Labels: Task, db, enhancement, frontend, teamwork

#128 Bhbc 864
  api/src/utils/code-utils.ts
  app/src/components/fields/AutocompleteField.tsx
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectCoordinatorForm.test.tsx.snap
Labels: BioHubBC, Story

#129 Remove unused code
  api/src/models/activity.ts
  api/src/models/survey.ts
  api/src/models/template.ts
  api/src/openapi/components/tags.ts
  api/src/openapi/schemas/activity.ts
  api/src/openapi/schemas/survey.ts
  api/src/openapi/schemas/template.ts
  api/src/paths/activity.ts
  api/src/paths/activity/{activityId}.ts
  api/src/paths/survey.ts
  api/src/paths/survey/{surveyId}.ts
  api/src/paths/template.ts
  api/src/paths/template/{templateId}.ts
  api/src/queries/activity-queries.ts
  api/src/queries/survey-queries.ts
  api/src/queries/template-queries.ts
Labels: technical debt

#127 Implement Objectives section in Project View Page
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
Labels: BioHubBC, Story, enhancement, frontend

#126 BHBC-873
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/queries/code-queries.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  api/src/utils/code-utils.ts
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectDetailsForm.test.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useBioHubApi-interfaces.ts
Labels: BioHubBC, Story

#131 Fix wrap issue in objectives section
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
Labels: bug, frontend

#132 Make default show no iucn classifications
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
Labels: enhancement, forms, frontend

#130 Fix map stuff
  api/src/database/db.ts
  api/src/errors/CustomError.ts
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/utils/MapEditControls.tsx
Labels: BioHubBC, bug, enhancement, frontend

#134 BHBC-866: Date improvements
  app/package.json
  app/src/constants/dateFormats.ts
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/utils/YupValidations.ts
Labels: BioHubBC, Story

#135 Add tests to location boundary and fix test warnings
  app/src/components/map/MapContainer.test.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
Labels: enhancement, frontend, technical debt

#138 Fix word break issue in project coordinator section (view page)
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectCoordinator.test.tsx.snap
Labels: bug, frontend

#140 Refactor and clean up code duplication
  app/src/AppRouter.tsx
  app/src/components/layout/Header.tsx
  app/src/components/layout/__snapshots__/Header.test.tsx.snap
  app/src/features/projects/ProjectsRouter.tsx
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/test-helpers/projectCodes.ts
  app/src/test-helpers/projectWithDetailsData.ts
Labels: enhancement, frontend, technical debt

#141 Implement IUCN Classification section to View Project page
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/interfaces/project-interfaces.ts
  app/src/test-helpers/projectWithDetailsData.ts
Labels: BioHubBC, Story, enhancement, forms, frontend

#143 Code smells fixes
  api/src/utils/code-utils.ts
  api/src/utils/template-utils.test.ts
  api/src/utils/template-utils.ts
  app/src/App.tsx
  app/src/hooks/useBioHubApi.ts
  app/src/rjsf/business-rules/customErrorTransformer.ts
  app/src/utils/KeycloakEventHandler.ts
Labels: bug, enhancement

#145 BHBC-876: Species view component
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/paths/projects.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/features/projects/ProjectsLayout.tsx
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/Species.tsx
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Species.test.tsx.snap
  app/src/interfaces/project-interfaces.ts
  app/src/test-helpers/projectWithDetailsData.ts
  app/src/utils/MapEditControls.tsx
Labels: BioHubBC, Story

#148 Implement Funding section to View Project page
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/constants/dateFormats.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/FundingSource.test.tsx.snap
  app/src/interfaces/project-interfaces.ts
  app/src/test-helpers/projectWithDetailsData.ts
Labels: BioHubBC, Story, Task, enhancement, frontend

#144 Refactor to reduce duplication
  app/src/components/fields/StartEndDateFields.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
Labels: technical debt

#149 Code Cleanup
  api/src/openapi/root-api-doc.ts
  api/src/queries/code-queries.ts
  api/src/utils/code-utils.ts
Labels: technical debt

#147 Caveats/bhbc 925
  app/src/components/fields/ReadMoreField.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
Labels: BioHubBC, bug

#150 Fix for sonar quality gate failing
  .sonarcloud.properties
  api/src/constants/codes.ts
  api/src/utils/code-utils.ts
Labels: technical debt

#151 Add support for custom yup methods
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/ProjectSpeciesForm.tsx
  app/src/types/yup.d.ts
  app/src/utils/YupSchema.ts
  app/src/utils/YupValidations.ts
Labels: BioHubBC, Story

#154 Breakout the Partnership section from the Funding section in the Create Project form
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project.ts
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectFundingForm.test.tsx
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/ProjectPartnershipsForm.test.tsx
  app/src/features/projects/components/ProjectPartnershipsForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectPartnershipsForm.test.tsx.snap
  app/src/interfaces/useBioHubApi-interfaces.ts
Labels: BioHubBC, Task, enhancement, frontend

#155 Implement the Partnership section to the Project View page
  api/src/models/project.test.ts
  api/src/models/project.ts
  api/src/paths/project/{projectId}.ts
  api/src/queries/project-queries.test.ts
  api/src/queries/project-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
  app/src/interfaces/project-interfaces.ts
  app/src/test-helpers/projectWithDetailsData.ts
Labels: BioHubBC, Story, enhancement, frontend

#156 BHBC-876: Update species view component
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/Species.tsx
  app/src/features/projects/view/components/__snapshots__/Species.test.tsx.snap
Labels: BioHubBC, Story

#153 BHBC-620: Cleanup/refactor
  api/src/models/media.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/codes.ts
  api/src/paths/permit-no-sampling.ts
  api/src/paths/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/paths/projects.ts
  api/src/paths/projects/{projectId}/artifacts/upload.test.ts
  api/src/paths/projects/{projectId}/artifacts/{fileName}/download.ts
  api/src/queries/codes/code-queries.ts
  api/src/queries/permit-no-sampling/permit-no-sampling-queries.test.ts
  api/src/queries/permit-no-sampling/permit-no-sampling-queries.ts
  api/src/queries/project/project-create-queries.test.ts
  api/src/queries/project/project-create-queries.ts
  api/src/queries/project/project-view-queries.test.ts
  api/src/queries/project/project-view-queries.ts
  api/src/utils/code-utils.ts
  api/src/utils/file-utils.ts
  app/src/components/form/FormContainer.tsx
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/ProjectSurveys.tsx
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/Species.tsx
  app/src/hooks/api/useAxios.ts
  app/src/hooks/api/useCodesApi.ts
  app/src/hooks/api/useProjectApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/project-interfaces.ts
  app/src/interfaces/useBioHubApi-interfaces.ts
  app/src/interfaces/useCodesApi.interface.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/rjsf/business-rules/customValidation.ts
  app/src/test-helpers/code-helpers.ts
  app/src/test-helpers/project-helpers.ts
Labels: BioHubBC, Story

#159 BHBC: 942 - Fix partnerships UI
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
Labels: BioHubBC, Task, enhancement, frontend

#160 Edit Project Coordinator section in the Project View page
  api/src/models/project.test.ts
  api/src/models/project.ts
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/__snapshots__/EditDialog.test.tsx.snap
  app/src/constants/i18n.ts
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectCoordinator.test.tsx.snap
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/project-helpers.ts
Labels: BioHubBC, Story, enhancement, frontend

#162 Edit General Information section in the View Project page
  api/src/models/project.ts
  app/src/constants/i18n.ts
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectCoordinator.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
  app/src/test-helpers/code-helpers.ts
  app/src/utils/ProjectStepComponents.test.tsx
  app/src/utils/ProjectStepComponents.tsx
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, Story, enhancement, frontend

#163 Front-end tests for Edit Modal
  app/src/components/dialog/EditDialog.test.tsx
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/__snapshots__/EditDialog.test.tsx.snap
Labels: BioHubBC, Story

#164 Location boundary edit (Frontend)
  app/src/constants/i18n.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
Labels: enhancement, frontend

#166 Partnerships edit (Frontend)
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/queries/project/project-update-queries.test.ts
  api/src/queries/project/project-update-queries.ts
  api/src/queries/project/project-view-queries.test.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/project/project-view-update-queries.test.ts
  api/src/queries/project/project-view-update-queries.ts
  app/package.json
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/__snapshots__/EditDialog.test.tsx.snap
  app/src/constants/i18n.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
Labels: enhancement, frontend

#167 [BHBC-899] Align Create Project Form to the Design Spec
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/styles.scss
  app/src/themes/appTheme.ts
Labels: BioHubBC, Task

#168 First Submission for CLAMAV BC and DC
  containers/clamav/.gitignore
  containers/clamav/Dockerfile
  containers/clamav/README.md
  containers/clamav/client/README.md
  containers/clamav/client/getversion.js
  containers/clamav/client/package-lock.json
  containers/clamav/client/package.json
  containers/clamav/client/ping.js
  containers/clamav/client/sample_files/RM_doggo.png
  containers/clamav/client/scandirectory.js
  containers/clamav/client/scanfile.js
  containers/clamav/config/clamd.conf
  containers/clamav/config/freshclam.conf
  containers/clamav/openshift/templates/clamav-bc.yaml
  containers/clamav/openshift/templates/clamav-dc.yaml
Labels: BioHubBC, Story

#171 BHBC-919
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-update-queries.ts
  api/src/queries/project/project-view-queries.ts
  app/src/constants/i18n.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectCoordinator.test.tsx.snap
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, Story

#172 IUCN Frontend - Wiring
  api/src/models/project-update.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-update-queries.test.ts
  api/src/queries/project/project-update-queries.ts
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/__snapshots__/EditDialog.test.tsx.snap
  app/src/constants/i18n.ts
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/themes/appTheme.ts
Labels: BioHubBC, Task, enhancement, frontend

#173 Edit the IUCN Classification section in the Project View page
  api/src/models/project-update.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/themes/appTheme.ts
Labels: BioHubBC, Story, enhancement

#175 Edit the Species section in the View Project page
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/Species.tsx
Labels: BioHubBC, Story, enhancement

#174 BHBC-947
  database/src/migrations/20210225205948_biohub_release_0.9.ts
  database/src/migrations/release.0.9/api_get_context_user_id.sql
  database/src/migrations/release.0.9/api_set_context.sql
  database/src/migrations/release.0.9/biohub.sql
  database/src/migrations/release.0.9/create_spatial_extensions.psql
  database/src/migrations/release.0.9/db_setup_up.sql
  database/src/migrations/release.0.9/populate_activity.sql
  database/src/migrations/release.0.9/populate_climate_change_initiatives.sql
  database/src/migrations/release.0.9/populate_first_nations.sql
  database/src/migrations/release.0.9/populate_funding_source.sql
  database/src/migrations/release.0.9/populate_icun_classifications.sql
  database/src/migrations/release.0.9/populate_investment_action_category.sql
  database/src/migrations/release.0.9/populate_management_action_type.sql
  database/src/migrations/release.0.9/populate_project_type.sql
  database/src/migrations/release.0.9/populate_system_constants_dev.sql
  database/src/migrations/release.0.9/populate_user_identity_source.sql
  database/src/migrations/release.0.9/project_audit_triggers.sql
  database/src/migrations/release.0.9/project_dapi_views.sql
  database/src/migrations/release.0.9/project_journal_triggers.sql
  database/src/migrations/release.0.9/smoketest_release.sql
  database/src/migrations/release.0.9/tr_audit_trigger.sql
  database/src/migrations/release.0.9/tr_journal_trigger.sql
  database/src/migrations/release.0.9/tr_project_funding_source.sql
Labels: BioHubBC, Story

#177 Edit Partnerships section in the Project View page
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/Species.tsx
Labels: BioHubBC, Story, enhancement, frontend

#176 Full flow of editing objectives
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-update-queries.test.ts
  api/src/queries/project/project-update-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
Labels: BioHubBC, Story

#179 [BHBC-899] Align Create Project Form to the Design Spec
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, Task

#178 UI fixes and test additions
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/ErrorDialog.tsx
  app/src/components/dialog/YesNoDialog.tsx
  app/src/components/dialog/__snapshots__/EditDialog.test.tsx.snap
  app/src/components/dialog/__snapshots__/ErrorDialog.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/test-helpers/project-helpers.ts
  app/src/themes/appTheme.ts
Labels: bug, enhancement, frontend, technical debt

#181 Bhbc 913
  api/src/queries/project/project-view-queries.ts
  app/package-lock.json
  app/package.json
  app/src/components/fields/DollarAmountField.test.tsx
  app/src/components/fields/DollarAmountField.tsx
  app/src/components/fields/__snapshots__/DollarAmountField.test.tsx.snap
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/__snapshots__/FundingSource.test.tsx.snap
  app/src/utils/Utils.ts
Labels: BioHubBC, bug

#182 BHBC-926: Add prompt to cancel create project workflow
  api/src/models/project-update.ts
  app/src/features/projects/CreateProjectPage.tsx
Labels: BioHubBC, bug

#183 Edit location section on the Project view
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/queries/generate-geometry-collection.ts
  api/src/queries/project/project-create-queries.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  api/src/queries/project/project-update-queries.test.ts
  api/src/queries/project/project-update-queries.ts
  api/src/queries/project/project-view-queries.test.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/project/project-view-update-queries.test.ts
  api/src/queries/project/project-view-update-queries.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
Labels: BioHubBC, Story, enhancement, frontend

#186 wrapifadditional component tests
  app/src/rjsf/templates/WrapIfAdditional.test.tsx
  app/src/rjsf/templates/__snapshots__/WrapIfAdditional.test.tsx.snap
Labels: enhancement, frontend, technical debt

#188 Remove unused files (didn't realize they were unused before)
  app/src/components/form/FormContainer.tsx
  app/src/rjsf/components/AddButton.tsx
  app/src/rjsf/components/IconButton.tsx
  app/src/rjsf/templates/ArrayFieldTemplate.tsx
  app/src/rjsf/templates/FieldTemplate.tsx
  app/src/rjsf/templates/ObjectFieldTemplate.tsx
  app/src/rjsf/templates/WrapIfAdditional.test.tsx
  app/src/rjsf/templates/WrapIfAdditional.tsx
  app/src/rjsf/templates/__snapshots__/WrapIfAdditional.test.tsx.snap
Labels: frontend, technical debt
