Repository bcgov/biohubbc, pull requests merged in 2021-05, with the labels that each got.

#271 Study area form, general information form, proprietary data form, and agreements form component (surveys)
  app/src/components/fields/StartEndDateFields.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/CreateSurveySection.tsx
  app/src/features/surveys/components/AgreementsForm.test.tsx
  app/src/features/surveys/components/AgreementsForm.tsx
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/ProprietaryDataForm.test.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/__snapshots__/AgreementsForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, Task, enhancement, forms, frontend

#274 Some missing surveys-related tests
  api/src/paths/codes.test.ts
  api/src/paths/permit-no-sampling.test.ts
  api/src/paths/user/self.test.ts
  app/src/features/surveys/CreateSurveyPage.test.tsx
  app/src/features/surveys/CreateSurveySection.test.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/__snapshots__/CreateSurveySection.test.tsx.snap
Labels: BioHubBC, enhancement, frontend, not using any openshift resources, technical debt

#277 xl not lg
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
Labels: enhancement, frontend

#278 BHBC-1023: Front end work for - Create Survey API and connect to Save and exit button
  app/src/constants/i18n.ts
  app/src/features/projects/create/CreateProjectPage.test.tsx
  app/src/features/surveys/CreateSurveyPage.test.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/AgreementsForm.test.tsx
  app/src/features/surveys/components/AgreementsForm.tsx
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/ProprietaryDataForm.test.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/__snapshots__/AgreementsForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/hooks/api/useProjectApi.test.ts
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, Task, enhancement, forms, frontend, teamwork

#282 Updates to proprietary data section of create survey
  api/src/paths/codes.ts
  api/src/queries/codes/code-queries.test.ts
  api/src/queries/codes/code-queries.ts
  api/src/utils/code-utils.ts
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/ProprietaryDataForm.test.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/interfaces/useCodesApi.interface.ts
  app/src/test-helpers/code-helpers.ts
Labels: BioHubBC, Task, enhancement, frontend

#285 Update autocomplete field to allow single elements and string/numbers
  app/src/components/fields/AutocompleteField.tsx
  app/src/components/fields/AutocompleteFreeSoloField.tsx
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/ProprietaryDataForm.test.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
Labels: BioHubBC, Task, enhancement, frontend

#286 BHBC: 1033 -> First pass on survey view page (not wired with backend)
  app/src/components/surveys/SurveysList.test.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/features/projects/ProjectsRouter.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectSurveysListPage.tsx
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
Labels: BioHubBC, Story, enhancement, frontend

#288 Test more things and refactoring
  api/src/paths/draft.test.ts
  api/src/paths/draft.ts
  api/src/queries/users/system-role-queries.test.ts
  app/src/components/attachments/AttachmentsList.tsx
  app/src/components/surveys/SurveysList.test.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/features/admin/users/ActiveUsersList.tsx
  app/src/utils/tablePaginationUtils.ts
Labels: technical debt

#290 some tests
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/queries/survey/survey-create-queries.test.ts
Labels: BioHubBC, technical debt

#291 Viewing surveys in list and details on view page
  api/src/models/survey-view.ts
  api/src/openapi/schemas/survey.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/paths/project/{projectId}/surveys.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/queries/survey/survey-view-queries.test.ts
  api/src/queries/survey/survey-view-queries.ts
  app/src/components/surveys/SurveysList.test.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/ProjectSurveysListPage.test.tsx
  app/src/features/projects/view/ProjectSurveysListPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/SurveyProprietaryData.tsx
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
Labels: BioHubBC, Story, enhancement

#293 Edit general information survey metadata and other fixes/changes
  api/src/models/survey-create.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view-update.ts
  api/src/models/survey-view.ts
  api/src/openapi/schemas/survey.ts
  api/src/paths/draft/{draftId}/get.ts
  api/src/paths/project/{projectId}/attachments/list.ts
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/paths/project/{projectId}/surveys.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/queries/survey/survey-create-queries.test.ts
  api/src/queries/survey/survey-update-queries.ts
  api/src/queries/survey/survey-view-queries.test.ts
  api/src/queries/survey/survey-view-queries.ts
  api/src/queries/survey/survey-view-update-queries.test.ts
  api/src/queries/survey/survey-view-update-queries.ts
  app/src/components/dialog/YesNoDialog.tsx
  app/src/components/dialog/__snapshots__/YesNoDialog.test.tsx.snap
  app/src/constants/i18n.ts
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectSurveysListPage.tsx
  app/src/features/surveys/CreateSurveyPage.test.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/ProprietaryDataForm.test.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/SurveyProprietaryData.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
Labels: BioHubBC, Story, enhancement

#307 🤖 Transformers, dependabots in disguise
  api/package-lock.json
  database/package-lock.json
Labels: BioHubBC, dependencies

#306 survey list/create test
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/surveys.test.ts
  api/src/paths/project/{projectId}/surveys.ts
  api/src/paths/projects.ts
Labels: BioHubBC, enhancement, technical debt

#309 getAddSystemRolesHandler tests
  api/src/paths/user/{userId}/system-roles.test.ts
  api/src/paths/user/{userId}/system-roles.ts
Labels: BioHubBC, enhancement, not using any openshift resources, technical debt

#313 Add surveygeneralinformation tests
  app/src/features/surveys/view/components/SurveyGeneralInformation.test.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/__snapshots__/SurveyGeneralInformation.test.tsx.snap
Labels: BioHubBC, frontend, technical debt

#315 Add a map to the survey metadata to record survey boundary
  api/src/models/project-view.test.ts
  api/src/models/survey-create.test.ts
  api/src/models/survey-create.ts
  api/src/models/survey-view-update.test.ts
  api/src/models/survey-view-update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/queries/survey/survey-create-queries.test.ts
  api/src/queries/survey/survey-create-queries.ts
  api/src/queries/survey/survey-view-update-queries.ts
  app/src/components/boundary/MapBoundary.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
  app/src/utils/mapBoundaryUploadHelpers.ts
Labels: BioHubBC, Story, enhancement, forms, frontend

#317 system user and delete attachments api tests finished
  api/src/paths/project/{projectId}/attachments/{attachmentId}/delete.test.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/delete.ts
  api/src/paths/user/{userId}/system-roles.test.ts
  api/src/paths/user/{userId}/system-roles.ts
Labels: BioHubBC, enhancement, technical debt

#319 File size in the attachment table should only have 1 decimal #
  app/src/components/attachments/AttachmentsList.test.tsx
  app/src/components/attachments/AttachmentsList.tsx
Labels: BioHubBC, Task, bug, enhancement, frontend

#318 Edit survey metadata - study area
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/openapi/schemas/survey.ts
  api/src/queries/survey/survey-update-queries.test.ts
  api/src/queries/survey/survey-update-queries.ts
  app/src/constants/i18n.ts
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/interfaces/useProjectApi.interface.ts
  app/src/utils/mapBoundaryUploadHelpers.ts
Labels: BioHubBC, Story, enhancement, frontend

#323 Survey start date should not come before project start date
  app/src/components/fields/StartEndDateFields.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.test.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/types/yup.d.ts
  app/src/utils/YupSchema.ts
Labels: BioHubBC, Task, bug, enhancement, frontend, teamwork

#326 bhbc1064 -> updates to date stuff based on robin's feedback
  app/src/components/fields/StartEndDateFields.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
Labels: BioHubBC, enhancement, forms, frontend

#332 Unit tests!!!
  api/src/paths/project/{projectId}/attachments/{attachmentId}/getSignedUrl.test.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/getSignedUrl.ts
  api/src/queries/survey/survey-create-queries.test.ts
  api/src/queries/survey/survey-update-queries.test.ts
  api/src/queries/survey/survey-view-queries.test.ts
Labels: BioHubBC, not using any openshift resources, technical debt

#333 Add unit tests
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/{attachmentId}/getSignedUrl.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/{attachmentId}/getSignedUrl.ts
Labels: BioHubBC, enhancement, not using any openshift resources, technical debt

#335 More unit tests
  api/src/paths/project/{projectId}/attachments/upload.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/upload.test.ts
Labels: BioHubBC, enhancement, not using any openshift resources, technical debt

#336 More API Tests!!!
  api/src/openapi/schemas/project.ts
  api/src/paths/project/{projectId}/update.test.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/survey/survey-delete-queries.test.ts
  api/src/queries/survey/survey-update-queries.test.ts
Labels: technical debt
