Repository bcgov/biohubbc, pull requests merged in 2021-07, with the labels that each got.

#395 Stop new-tab link from triggering a page re-render
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/surveys/components/ProprietaryDataForm.tsx
Labels: not using any openshift resources

#393 Update search feature map popup with link and project view with statuses
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/paths/projects.ts
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/SearchFeaturePopup.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/features/admin/users/AccessRequestList.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/search/SearchPage.test.tsx
  app/src/hooks/api/useSearchApi.test.ts
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/pages/access/AccessRequestPage.tsx
  app/src/pages/access/BCeIDRequestForm.test.tsx
  app/src/pages/access/BCeIDRequestForm.tsx
  app/src/pages/access/__snapshots__/BCeIDRequestForm.test.tsx.snap
  app/src/test-helpers/project-helpers.ts
Labels: BioHubBC, bug, enhancement, frontend

#404 Display survey statuses on the survey list and view
  api/src/models/survey-view-update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/paths/project/{projectId}/surveys.test.ts
  api/src/paths/project/{projectId}/surveys.ts
  api/src/queries/survey/survey-view-queries.ts
  api/src/queries/survey/survey-view-update-queries.ts
  app/src/components/surveys/SurveysList.test.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/constants/misc.ts
  app/src/features/surveys/list/SurveysListPage.test.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyPage.test.tsx.snap
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
  database/src/migrations/20210708110000_survey_publish_timestamp.ts
Labels: BioHubBC, Task, enhancement, frontend

#406 Small test update
  api/src/models/occurrence-create.test.ts
  api/src/queries/occurrence/occurrence-create-queries.test.ts
Labels: not using any openshift resources

#402 Updates and addition of tests
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
Labels: BioHubBC, technical debt

#405 Implement permit fields in the survey metadata form
  api/src/models/survey-create.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view-update.ts
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/permits/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/queries/survey/survey-create-queries.test.ts
  api/src/queries/survey/survey-create-queries.ts
  api/src/queries/survey/survey-update-queries.test.ts
  api/src/queries/survey/survey-update-queries.ts
  api/src/queries/survey/survey-view-queries.test.ts
  api/src/queries/survey/survey-view-queries.ts
  api/src/queries/survey/survey-view-update-queries.ts
  app/src/features/surveys/CreateSurveyPage.test.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.test.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/__snapshots__/SurveyGeneralInformation.test.tsx.snap
  app/src/hooks/api/useSurveyApi.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
Labels: BioHubBC, Task, enhancement

#407 BHBC-1080: Part 2 (Unit tests and minor updates)
  api/src/paths/project/{projectId}/survey/permits/list.test.ts
  api/src/paths/project/{projectId}/survey/permits/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
Labels: documentation, enhancement, technical debt

#408 BHBC 1081: Implement funding to the survey metadata
  api/src/models/survey-create.ts
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view-update.test.ts
  api/src/models/survey-view-update.ts
  api/src/models/survey-view.test.ts
  api/src/models/survey-view.ts
  api/src/paths/project/{projectId}/attachments/list.ts
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/funding-sources/list.test.ts
  api/src/paths/project/{projectId}/survey/funding-sources/list.ts
  api/src/paths/project/{projectId}/survey/permits/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/queries/survey/survey-create-queries.test.ts
  api/src/queries/survey/survey-create-queries.ts
  api/src/queries/survey/survey-delete-queries.test.ts
  api/src/queries/survey/survey-delete-queries.ts
  api/src/queries/survey/survey-update-queries.test.ts
  api/src/queries/survey/survey-update-queries.ts
  api/src/queries/survey/survey-view-queries.ts
  api/src/queries/survey/survey-view-update-queries.ts
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/surveys/CreateSurveyPage.test.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.test.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyGeneralInformation.test.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/__snapshots__/SurveyGeneralInformation.test.tsx.snap
  app/src/hooks/api/useSurveyApi.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
Labels: Story, enhancement, frontend

#423 Tech Debt on Sprint Review Day
  app/src/hooks/api/useObservationApi.test.ts
  app/src/hooks/api/usePermitApi.test.ts
  app/src/hooks/api/useProjectApi.test.ts
  app/src/hooks/api/useProjectApi.ts
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, enhancement, frontend, technical debt

#425 Drawing a circlemarker or marker to create the project boundary creates an error on the map display
  app/src/components/map/MapContainer.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/utils/mapBoundaryUploadHelpers.ts
Labels: bug

#429 error with 'start date' - "cannot have survey start date before project start date'
  app/src/features/observations/BlockObservationPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/components/__snapshots__/GeneralInformationForm.test.tsx.snap
Labels: BioHubBC, bug, frontend

#430 Polish existing feature to select boundaries based on existing layers
  app/src/components/boundary/MapBoundary.tsx
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/WFSFeatureGroup.test.tsx
  app/src/components/map/WFSFeatureGroup.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/components/map/__snapshots__/WFSFeatureGroup.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/search/__snapshots__/SearchPage.test.tsx.snap
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, Task, enhancement, frontend

#431 Get fullscreen map working
  app/package-lock.json
  app/package.json
  app/src/components/map/MapContainer.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
  app/src/features/search/__snapshots__/SearchPage.test.tsx.snap
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, enhancement, frontend
