Repository bcgov/biohubbc, pull requests merged in 2021-06, with the labels that each got.

#340 Add tests for API
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
Labels: BioHubBC, technical debt

#347 Spatial Search and Project Filter
  api/src/openapi/schemas/geojson-feature.ts
  api/src/openapi/schemas/search.ts
  api/src/paths/projects.ts
  api/src/paths/search.test.ts
  api/src/paths/search.ts
  api/src/queries/project/project-view-queries.test.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/search-queries.test.ts
  api/src/queries/search-queries.ts
  app/src/AppRouter.tsx
  app/src/components/layout/Header.tsx
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/SearchFeaturePopup.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/components/search-filter/ProjectAdvancedFilters.tsx
  app/src/components/search-filter/SearchAdvancedFilters.tsx
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/search/SearchPage.test.tsx
  app/src/features/search/SearchPage.tsx
  app/src/features/search/__snapshots__/SearchPage.test.tsx.snap
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/hooks/api/useProjectApi.test.ts
  app/src/hooks/api/useProjectApi.ts
  app/src/hooks/api/useSearchApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/interfaces/useSearchApi.interface.ts
  app/src/utils/mapBoundaryUploadHelpers.ts
Labels: BioHubBC, Story, enhancement, frontend

#358 Block list!!!
  app/src/features/projects/ProjectsRouter.tsx
  app/src/features/surveys/view/SurveyObservations.tsx
  app/src/features/surveys/view/SurveyPage.test.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyPage.test.tsx.snap
  app/src/hooks/api/useObservationApi.test.ts
  app/src/hooks/api/useObservationApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useObservationApi.interface.ts
Labels: BioHubBC, Task, enhancement, frontend

#361 Enhance the docker-compose/makefile setup for running/reverting migrations
  Makefile
  database/.docker/db/Dockerfile.rollback
  database/src/migrations/20210225205948_biohub_release.ts
  docker-compose.yml
Labels: not using any openshift resources

#363 Build Moose observation forms based on prototype
  app/package-lock.json
  app/package.json
  app/src/constants/i18n.ts
  app/src/features/observations/BlockObservationPage.test.tsx
  app/src/features/observations/BlockObservationPage.tsx
  app/src/features/observations/__snapshots__/BlockObservationPage.test.tsx.snap
  app/src/features/observations/components/BlockObservationForm.tsx
  app/src/features/projects/ProjectsRouter.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/list/SurveysListPage.test.tsx
  app/src/features/surveys/list/SurveysListPage.tsx
  app/src/features/surveys/view/SurveyObservations.tsx
  app/src/features/surveys/view/SurveyPage.test.tsx
  app/src/features/surveys/view/__snapshots__/SurveyPage.test.tsx.snap
Labels: BioHubBC, Story, enhancement, forms, frontend

#364 Ability to retrieve actual block list data
  api/src/models/observation-view.test.ts
  api/src/models/observation-view.ts
  api/src/openapi/schemas/observation.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/list.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/list.ts
  api/src/queries/observation/observation-view-queries.test.ts
  api/src/queries/observation/observation-view-queries.ts
  app/src/components/attachments/AttachmentsList.tsx
  app/src/components/fields/StartEndDateFields.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/constants/dateTimeFormats.ts
  app/src/features/admin/users/AccessRequestList.tsx
  app/src/features/admin/users/ReviewAccessRequestForm.tsx
  app/src/features/observations/components/BlockObservationForm.tsx
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/create/CreateProjectPage.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/components/GeneralInformationForm.tsx
  app/src/features/surveys/view/SurveyObservations.test.tsx
  app/src/features/surveys/view/SurveyObservations.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/hooks/api/useObservationApi.test.ts
  app/src/hooks/api/useObservationApi.ts
  app/src/types/yup.d.ts
  app/src/utils/Utils.test.ts
  app/src/utils/Utils.ts
  app/src/utils/YupSchema.ts
Labels: BioHubBC, Story, enhancement

#368 add tests (api)
  api/src/paths/project/{projectId}/survey/{surveyId}/update.test.ts
Labels: BioHubBC, not using any openshift resources, technical debt

#369 bug fix for proprietary data section
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyProprietaryData.tsx
Labels: BioHubBC, bug, frontend

#365 Block observation get for update basic endpoint
  api/src/openapi/schemas/observation.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/{observationId}/update.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/{observationId}/update.ts
  api/src/queries/observation/observation-update-queries.test.ts
  api/src/queries/observation/observation-update-queries.ts
  app/src/constants/i18n.ts
  app/src/features/observations/BlockObservationPage.test.tsx
  app/src/features/observations/BlockObservationPage.tsx
  app/src/features/observations/__snapshots__/BlockObservationPage.test.tsx.snap
  app/src/features/observations/components/BlockObservationForm.tsx
  app/src/features/projects/ProjectsRouter.tsx
  app/src/features/surveys/view/SurveyObservations.tsx
  app/src/hooks/api/useObservationApi.ts
  app/src/interfaces/useObservationApi.interface.ts
  app/src/test-helpers/observation-helpers.ts
  testing/e2e/cypress/integration/KC_Login.spec.ts
Labels: BioHubBC, Task, enhancement

#370 make model consistent with anissas
  app/src/features/observations/BlockObservationPage.tsx
  app/src/interfaces/useObservationApi.interface.ts
  app/src/test-helpers/observation-helpers.ts
Labels: BioHubBC

#372 Throw errors in db connection
  api/src/database/db.ts
Labels: not using any openshift resources

#373 survey/{surveyId}/attachments/upload.ts test coverage
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/upload.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/upload.ts
Labels: BioHubBC, technical debt

#375 Delete survey functionality!!! 🗑️
  api/src/paths/project/{projectId}/survey/{surveyId}/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/delete.ts
  api/src/queries/survey/survey-attachments-queries.ts
  api/src/queries/survey/survey-delete-queries.test.ts
  api/src/queries/survey/survey-delete-queries.ts
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/hooks/api/useSurveyApi.ts
  database/README.md
  database/src/migrations/20210611115350_block_observation.ts
  database/src/migrations/20210618115350_delete_survey.ts
  database/src/migrations/release.0.18/smoketest_release.sql
Labels: BioHubBC, Story, db, enhancement, frontend

#378 Delete project functionality!!!
  api/src/paths/project/{projectId}/delete.test.ts
  api/src/paths/project/{projectId}/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/delete.ts
  api/src/queries/project/project-attachments-queries.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  api/src/queries/survey/survey-delete-queries.ts
  api/src/queries/survey/survey-view-queries.test.ts
  api/src/queries/survey/survey-view-queries.ts
  app/src/features/observations/components/BlockObservationForm.tsx
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/hooks/api/useProjectApi.test.ts
  app/src/hooks/api/useProjectApi.ts
  database/src/migrations/release.0.18/api_delete_project.sql
Labels: BioHubBC, Story, db, enhancement, frontend

#379 Fix location of project and survey delete buttons
  app/src/features/projects/view/ProjectDetails.test.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/surveys/view/SurveyDetails.test.tsx
  app/src/features/surveys/view/SurveyDetails.tsx
  app/src/features/surveys/view/SurveyPage.test.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/__snapshots__/SurveyPage.test.tsx.snap
Labels: BioHubBC, enhancement, frontend

#382 testing things that werent previously tested
  api/src/paths/project/{projectId}/attachments/upload.test.ts
  api/src/paths/project/{projectId}/attachments/upload.ts
  api/src/paths/project/{projectId}/survey/create.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/upload.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/create.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/{observationId}/update.test.ts
Labels: BioHubBC, technical debt

#383 Squash some bugs
  api/src/models/block-observation-create.test.ts
  api/src/models/block-observation-create.ts
  app/src/components/boundary/MapBoundary.tsx
  app/src/features/observations/BlockObservationPage.tsx
  app/src/features/observations/__snapshots__/BlockObservationPage.test.tsx.snap
  app/src/features/observations/components/BlockObservationForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/surveys/__snapshots__/CreateSurveyPage.test.tsx.snap
  app/src/features/surveys/components/ProprietaryDataForm.tsx
  app/src/features/surveys/components/__snapshots__/ProprietaryDataForm.test.tsx.snap
  app/src/features/surveys/components/__snapshots__/StudyAreaForm.test.tsx.snap
  app/src/features/surveys/view/__snapshots__/SurveyDetails.test.tsx.snap
  app/src/features/surveys/view/components/SurveyProprietaryData.tsx
  app/src/types/yup.d.ts
  app/src/utils/YupSchema.ts
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, bug

#388 Clustering polygons into points on a map
  api/src/paths/search.test.ts
  api/src/paths/search.ts
  api/src/queries/search-queries.test.ts
  api/src/queries/search-queries.ts
  app/package-lock.json
  app/package.json
  app/src/components/boundary/MapBoundary.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/search-filter/SearchAdvancedFilters.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/search/SearchPage.tsx
  app/src/features/search/__snapshots__/SearchPage.test.tsx.snap
  app/src/hooks/api/useSearchApi.ts
  app/src/utils/MapEditControls.tsx
  database/src/migrations/20210625115350_project_add_publish_timestamp.ts
Labels: BioHubBC, Story, enhancement, frontend

#391 Display Project Statuses on Project List
  api/src/paths/projects.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/search-queries.ts
  app/src/constants/misc.ts
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, Story, enhancement, frontend
