Repository bcgov/biohubbc, pull requests merged in 2021-02, with the labels that each got.

#70 Add troubleshooting section to readme
  README.md
Labels: documentation, enhancement

#75 [BHBC-742] Basic Common Components (BC Gov Styling)
  app/src/assets/fonts/BCSans/BCSans-Bold.woff
  app/src/assets/fonts/BCSans/BCSans-Bold.woff2
  app/src/assets/fonts/BCSans/BCSans-BoldItalic.woff
  app/src/assets/fonts/BCSans/BCSans-BoldItalic.woff2
  app/src/assets/fonts/BCSans/BCSans-Italic.woff
  app/src/assets/fonts/BCSans/BCSans-Italic.woff2
  app/src/assets/fonts/BCSans/BCSans-Regular.woff
  app/src/assets/fonts/BCSans/BCSans-Regular.woff2
  app/src/assets/fonts/BCSans/LICENSE_OFL.txt
  app/src/assets/images/gov-bc-logo-horiz.png
  app/src/assets/images/gov-bc-logo-vert.png
  app/src/components/layout/Footer.tsx
  app/src/components/layout/Header.test.tsx
  app/src/components/layout/Header.tsx
  app/src/components/layout/__snapshots__/Footer.test.tsx.snap
  app/src/components/layout/__snapshots__/Header.test.tsx.snap
  app/src/layouts/PublicLayout.tsx
  app/src/styles.scss
  app/src/styles/Footer.scss
  app/src/styles/Header.scss
  app/src/styles/colours.scss
  app/src/styles/fonts.scss
  app/src/themes/appTheme.ts
Labels: enhancement, frontend

#72 Add map container component, edit/draw controls
  app/package-lock.json
  app/package.json
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/__snapshots__/MapContainer.test.tsx.snap
  app/src/setupTests.ts
  app/src/utils/MapEditControls.test.tsx
  app/src/utils/MapEditControls.tsx
Labels: enhancement, frontend

#80 767: Adding spatial columns
  database/src/migrations/20210224144754_alter_project_table.ts
  database/src/seeds/02_db_system_users.ts
Labels: db, enhancement, migration
