Repository bcgov/biohubbc, pull requests merged in 2021-04, with the labels that each got.

#191 better test coverage
  app/src/components/fields/DollarAmountField.test.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectPermitForm.test.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
Labels: enhancement, frontend, technical debt

#192 remove customvalidation and other unused files
  app/src/rjsf/business-rules/customErrorTransformer.ts
  app/src/rjsf/business-rules/customValidation.ts
  app/src/utils/FunctionUtils.ts
  app/src/utils/JsonUtils.ts
  app/src/utils/Utils.test.ts
Labels: technical debt

#194 Editing pop-ups allow users to click out of it without saving changes
  app/src/components/dialog/EditDialog.test.tsx
  app/src/components/dialog/EditDialog.tsx
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/Species.tsx
Labels: BioHubBC, bug, enhancement, frontend

#197 BHBC-964: Initial structure
  app/src/components/attachments/FileUpload.tsx
  app/src/components/dialog/ComponentDialog.test.tsx
  app/src/components/dialog/ComponentDialog.tsx
  app/src/components/dialog/__snapshots__/ComponentDialog.test.tsx.snap
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/__snapshots__/ProjectAttachments.test.tsx.snap
Labels: BioHubBC, Story

#198 First commit
  .github/workflows/cleanClosedPR.yml
  .github/workflows/deploy.yml
  .github/workflows/deployStatic.yml
Labels: BioHubBC, Task

#196 Error message that users can have duplicate entries on IUCN, species and permits
  app/src/features/projects/components/ProjectIUCNForm.test.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/ProjectLocationForm.test.tsx
  app/src/features/projects/components/ProjectPermitForm.test.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/ProjectSpeciesForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/components/Species.test.tsx
  app/src/types/yup.d.ts
  app/src/utils/YupSchema.ts
Labels: BioHubBC, bug, enhancement, frontend

#203 BHBC-964: File upload component + tests
  app/package-lock.json
  app/package.json
  app/src/components/attachments/DropZone.test.tsx
  app/src/components/attachments/DropZone.tsx
  app/src/components/attachments/FileUpload.test.tsx
  app/src/components/attachments/FileUpload.tsx
  app/src/components/attachments/__snapshots__/DropZone.test.tsx.snap
  app/src/components/attachments/__snapshots__/FileUpload.test.tsx.snap
  app/src/components/dialog/ComponentDialog.tsx
  app/src/hooks/api/useProjectApi.ts
Labels: BioHubBC, Story

#208 BHBC-964: Additional UI tweaks and test updates
  app/src/components/attachments/DropZone.tsx
  app/src/components/attachments/FileUpload.test.tsx
  app/src/components/attachments/FileUpload.tsx
  app/src/components/attachments/__snapshots__/DropZone.test.tsx.snap
  app/src/components/attachments/__snapshots__/FileUpload.test.tsx.snap
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/__snapshots__/ProjectAttachments.test.tsx.snap
Labels: BioHubBC, Story

#209 add public layout tests
  app/src/layouts/PublicLayout.test.tsx
  app/src/layouts/__snapshots__/PublicLayout.test.tsx.snap
Labels: frontend, technical debt

#213 BHBC-969
  database/src/migrations/20210225205948_biohub_release_0.10.ts
  database/src/migrations/release.0.10/api_get_context_user_id.sql
  database/src/migrations/release.0.10/api_set_context.sql
  database/src/migrations/release.0.10/biohub.sql
  database/src/migrations/release.0.10/create_spatial_extensions.psql
  database/src/migrations/release.0.10/populate_activity.sql
  database/src/migrations/release.0.10/populate_climate_change_initiatives.sql
  database/src/migrations/release.0.10/populate_first_nations.sql
  database/src/migrations/release.0.10/populate_funding_source.sql
  database/src/migrations/release.0.10/populate_icun_classifications.sql
  database/src/migrations/release.0.10/populate_investment_action_category.sql
  database/src/migrations/release.0.10/populate_management_action_type.sql
  database/src/migrations/release.0.10/populate_project_role.sql
  database/src/migrations/release.0.10/populate_project_type.sql
  database/src/migrations/release.0.10/populate_system_role.sql
  database/src/migrations/release.0.10/populate_user_identity_source.sql
  database/src/migrations/release.0.10/project_audit_triggers.sql
  database/src/migrations/release.0.10/project_dapi_views.sql
  database/src/migrations/release.0.10/project_journal_triggers.sql
  database/src/migrations/release.0.10/smoketest_release.sql
  database/src/migrations/release.0.10/tr_audit_trigger.sql
  database/src/migrations/release.0.10/tr_journal_trigger.sql
  database/src/migrations/release.0.10/tr_project_funding_source.sql
  database/src/migrations/release.0.9/db_setup_up.sql
  database/src/migrations/release.0.9/populate_system_constants_dev.sql
  database/src/migrations/release.0.9/smoketest_release.sql
Labels: BioHubBC, Story

#214 Implement the designs for listing attachments & Enhance file upload end-points
  api/src/models/project-attachments.ts
  api/src/paths/project.ts
  api/src/paths/project/{projectId}/attachments/list.ts
  api/src/paths/project/{projectId}/attachments/upload.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/delete.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/signedUrl.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/projects/{projectId}/artifacts/list.ts
  api/src/paths/projects/{projectId}/artifacts/{fileName}/download.ts
  api/src/queries/project/project-attachments-queries.ts
  api/src/utils/file-utils.ts
  api/src/utils/shared-api-responses.ts
  app/src/components/attachments/AttachmentsList.tsx
  app/src/components/attachments/FileUpload.test.tsx
  app/src/components/attachments/FileUpload.tsx
  app/src/constants/i18n.ts
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/__snapshots__/ProjectAttachments.test.tsx.snap
  app/src/hooks/api/useProjectApi.ts
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, Story, enhancement, frontend

#211 BHBC-914: Save drafts
  api/src/database/db.ts
  api/src/models/project-create.ts
  api/src/openapi/schemas/draft.test.ts
  api/src/openapi/schemas/draft.ts
  api/src/paths/draft.ts
  api/src/queries/draft-queries.test.ts
  api/src/queries/draft-queries.ts
  api/src/queries/project/project-create-queries.test.ts
  api/src/queries/project/project-update-queries.test.ts
  app/src/components/attachments/FileUpload.test.tsx
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/ErrorDialog.test.tsx
  app/src/components/dialog/ErrorDialog.tsx
  app/src/components/dialog/__snapshots__/ErrorDialog.test.tsx.snap
  app/src/constants/dateFormats.ts
  app/src/constants/i18n.ts
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectDraftForm.test.tsx
  app/src/features/projects/components/ProjectDraftForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDraftForm.test.tsx.snap
  app/src/hooks/api/useDraftApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useDraftApi.interface.ts
  docker-compose.yml
Labels: BioHubBC, Story

#217 Add missing attachments tests
  api/src/models/project-attachments.test.ts
  api/src/queries/project/project-attachments-queries.test.ts
  api/src/utils/file-utils.test.ts
  api/src/utils/file-utils.ts
  api/src/utils/shared-api-responses.test.ts
  app/package.json
  app/src/App.test.tsx
  app/src/components/attachments/AttachmentsList.test.tsx
  app/src/components/attachments/AttachmentsList.tsx
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/__snapshots__/ProjectAttachments.test.tsx.snap
Labels: technical debt

#218 Cleanup 😄🗑️
  app/src/App.tsx
  app/src/hooks/useQuery.ts
  app/src/utils/KeycloakEventHandler.ts
Labels: technical debt

#219 BHBC-964
  api/package.json
  api/src/app.ts
  app/src/components/attachments/DropZone.tsx
  app/src/components/attachments/FileUpload.test.tsx
  app/src/components/attachments/FileUpload.tsx
  app/src/components/attachments/__snapshots__/FileUpload.test.tsx.snap
  docker-compose.yml
  env_config/env.docker
Labels: BioHubBC, Story

#221 Add missing tests and fix FE warning
  api/src/models/project-create.test.ts
  api/src/models/project-create.ts
  api/src/models/project-update.test.ts
  api/src/paths/project/{projectId}/attachments/upload.ts
  app/src/components/attachments/AttachmentsList.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
Labels: technical debt

#223 [BHBC-965] Project Page UI Clean-up / Refactor Markup
  app/src/components/layout/Footer.tsx
  app/src/components/layout/Header.tsx
  app/src/components/layout/__snapshots__/Footer.test.tsx.snap
  app/src/components/layout/__snapshots__/Header.test.tsx.snap
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.tsx
  app/src/features/projects/view/components/__snapshots__/FundingSource.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Species.test.tsx.snap
  app/src/layouts/__snapshots__/PublicLayout.test.tsx.snap
  app/src/styles.scss
  app/src/styles/Footer.scss
  app/src/styles/Header.scss
  app/src/themes/appTheme.ts
Labels: BioHubBC, Task

#222 Implement functionality to view draft projects in the project list
  api/src/paths/drafts.ts
  api/src/queries/draft-queries.test.ts
  api/src/queries/draft-queries.ts
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/hooks/api/useDraftApi.ts
  app/src/interfaces/useDraftApi.interface.ts
Labels: BioHubBC, Story, enhancement, frontend

#225 Code cleanup and tests
  api/src/models/permit-no-sampling.test.ts
  api/src/models/project-create.test.ts
  app/package.json
  app/src/themes/rjsfTheme.ts
  app/src/utils/MapEditControls.test.tsx
  app/src/utils/MapEditControls.tsx
  app/src/utils/ProjectStepComponents.test.tsx
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: technical debt

#227 add delete confirmation dialog on attachment delete
  api/src/app.ts
  app/src/components/attachments/AttachmentsList.tsx
  app/src/features/projects/view/ProjectAttachments.test.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/interfaces/useProjectApi.interface.ts
Labels: BioHubBC, enhancement, frontend

#230 BHBC-914: Drafts now save WIP steps correctly.
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
Labels: BioHubBC, Story

#229 API Tests
  api/src/models/media.ts
  api/src/models/project-create.test.ts
  api/src/models/project-create.ts
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view-update.test.ts
  api/src/models/project-view.test.ts
Labels: technical debt

#233 Add missing tests to code queries file
  api/src/queries/codes/code-queries.test.ts
Labels: not using any openshift resources, technical debt

#234 add missing api tests
  api/src/utils/shared-api-docs.test.ts
Labels: not using any openshift resources, technical debt

#235 Add missing FE tests
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/__snapshots__/FundingSource.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
Labels: not using any openshift resources, technical debt

#232 Build time improvements (maybe??)
  app/src/App.tsx
  app/src/components/attachments/AttachmentsList.tsx
  app/src/components/attachments/DropZone.tsx
  app/src/components/attachments/FileUpload.tsx
  app/src/components/dialog/ComponentDialog.test.tsx
  app/src/components/dialog/ComponentDialog.tsx
  app/src/components/dialog/EditDialog.test.tsx
  app/src/components/dialog/EditDialog.tsx
  app/src/components/dialog/ErrorDialog.tsx
  app/src/components/dialog/YesNoDialog.tsx
  app/src/components/fields/AutocompleteField.tsx
  app/src/components/fields/DollarAmountField.tsx
  app/src/components/fields/MultiAutocompleteField.tsx
  app/src/components/fields/MultiAutocompleteFieldVariableSize.tsx
  app/src/components/fields/ReadMoreField.tsx
  app/src/components/fields/StartEndDateFields.tsx
  app/src/components/layout/Footer.tsx
  app/src/components/layout/Header.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/ProjectsLayout.tsx
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectDraftForm.tsx
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/ProjectPartnershipsForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/ProjectSpeciesForm.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/view/ProjectAttachments.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/ProjectSurveys.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.tsx
  app/src/layouts/AuthLayout.tsx
  app/src/layouts/PublicLayout.tsx
  app/src/pages/403/AccessDenied.tsx
  app/src/pages/404/NotFoundPage.tsx
  app/src/rjsf/README.md
  app/src/rjsf/widgets/MultiSelectAutocomplete.test.tsx
  app/src/rjsf/widgets/MultiSelectAutocomplete.tsx
Labels: enhancement

#237 Adding a new funding source test case
  app/src/components/fields/DollarAmountField.tsx
  app/src/components/fields/StartEndDateFields.tsx
  app/src/components/fields/__snapshots__/DollarAmountField.test.tsx.snap
  app/src/features/projects/components/ProjectFundingItemForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: not using any openshift resources, technical debt

#238 Implement functionality to edit draft projects
  api/src/openapi/schemas/draft.ts
  api/src/paths/draft/{draftId}/delete.ts
  api/src/paths/draft/{draftId}/get.ts
  api/src/paths/project/{projectId}/attachments/list.ts
  api/src/paths/project/{projectId}/attachments/upload.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/delete.ts
  api/src/paths/project/{projectId}/attachments/{attachmentId}/getSignedUrl.ts
  api/src/queries/draft-queries.test.ts
  api/src/queries/draft-queries.ts
  api/src/utils/shared-api-docs.test.ts
  api/src/utils/shared-api-docs.ts
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/hooks/api/useDraftApi.ts
  app/src/hooks/useQuery.ts
  app/src/interfaces/useDraftApi.interface.ts
Labels: enhancement, frontend

#241 Implement Permit session in the Create Project and View Project page
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/queries/project/project-view-queries.test.ts
  api/src/queries/project/project-view-queries.ts
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectPermits.test.tsx
  app/src/features/projects/view/components/ProjectPermits.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectPermits.test.tsx.snap
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/project-helpers.ts
Labels: BioHubBC, Task, enhancement, frontend

#242 [BHBC-965] Project Page UI Clean-up / Refactor Markup
  app/src/components/layout/Header.tsx
  app/src/constants/i18n.ts
  app/src/features/projects/components/ProjectFundingForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingForm.test.tsx.snap
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectPage.test.tsx.snap
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/features/projects/view/components/FundingSource.tsx
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/projects/view/components/Partnerships.test.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/ProjectCoordinator.test.tsx
  app/src/features/projects/view/components/ProjectCoordinator.tsx
  app/src/features/projects/view/components/ProjectObjectives.test.tsx
  app/src/features/projects/view/components/ProjectObjectives.tsx
  app/src/features/projects/view/components/Species.test.tsx
  app/src/features/projects/view/components/Species.tsx
  app/src/features/projects/view/components/__snapshots__/FundingSource.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/LocationBoundary.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectCoordinator.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectObjectives.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Species.test.tsx.snap
  app/src/styles.scss
  app/src/themes/appTheme.ts
Labels: enhancement

#244 Edit the Permits section in the View Project page
  api/src/models/project-create.test.ts
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  api/src/queries/project/project-update-queries.test.ts
  api/src/queries/project/project-update-queries.ts
  app/src/constants/i18n.ts
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/view/ProjectDetails.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/ProjectPermits.test.tsx
  app/src/features/projects/view/components/ProjectPermits.tsx
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/ProjectPermits.test.tsx.snap
  app/src/interfaces/useProjectApi.interface.ts
  app/src/types/yup.d.ts
  app/src/utils/YupSchema.ts
Labels: BioHubBC, Story, enhancement, frontend

#245 User denied access to BioHub
  app/src/AppRouter.tsx
  app/src/pages/403/AccessDenied.tsx
  app/src/pages/403/__snapshots__/AccessDenied.test.tsx.snap
  app/src/pages/404/NotFoundPage.tsx
  app/src/pages/404/__snapshots__/NotFoundPage.test.tsx.snap
Labels: BioHubBC, Task, enhancement, frontend, not using any openshift resources

#249 Active Users List
  api/src/paths/users.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/users/user-queries.test.ts
  api/src/queries/users/user-queries.ts
  app/src/features/admin/users/ActiveUsersList.test.tsx
  app/src/features/admin/users/ActiveUsersList.tsx
  app/src/features/admin/users/ManageUsersPage.test.tsx
  app/src/features/admin/users/ManageUsersPage.tsx
  app/src/hooks/api/useUserApi.ts
Labels: BioHubBC, Task, enhancement, frontend

#252 Add test coverage ✔️
  app/src/features/projects/view/components/FundingSource.test.tsx
  app/src/pages/404/NotFoundPage.test.tsx
Labels: frontend, not using any openshift resources, technical debt

#251 Add permit type field to permit section (create, view, and edit)
  api/src/models/project-create.test.ts
  api/src/models/project-create.ts
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/paths/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/queries/project/project-create-queries.test.ts
  api/src/queries/project/project-create-queries.ts
  api/src/queries/project/project-update-queries.ts
  api/src/queries/project/project-view-queries.ts
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectPermitForm.test.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectPermitForm.test.tsx.snap
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/ProjectPermits.test.tsx
  app/src/features/projects/view/components/ProjectPermits.tsx
  app/src/features/projects/view/components/__snapshots__/ProjectPermits.test.tsx.snap
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/project-helpers.ts
Labels: BioHubBC, Task, enhancement, frontend

#253 Various tests and cleanups
  api/src/queries/administrative-activity/administrative-activity-queries.test.ts
  app/package-lock.json
  app/package.json
  app/src/hooks/api/useCodesApi.test.ts
  app/src/hooks/api/useDraftApi.test.ts
  app/src/hooks/api/useUserApi.test.ts
  app/src/pages/200/RequestSubmitted.test.tsx
  app/src/pages/200/RequestSubmitted.tsx
  app/src/pages/403/AccessDenied.test.tsx
  app/src/pages/403/AccessDenied.tsx
  app/src/pages/access/AccessRequestPage.test.tsx
  app/src/pages/access/AccessRequestPage.tsx
  app/src/pages/access/__snapshots__/AccessRequestPage.test.tsx.snap
Labels: not using any openshift resources, teamwork, technical debt

#256 add tests
  app/src/hooks/api/useProjectApi.test.ts
Labels: frontend, not using any openshift resources, technical debt

#257 Allow users to navigate the Create Project form out of order
  app/src/components/fields/AutocompleteField.tsx
  app/src/components/fields/MultiAutocompleteFieldVariableSize.tsx
  app/src/components/fields/StartEndDateFields.tsx
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectCoordinatorForm.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectFundingForm.test.tsx
  app/src/features/projects/components/ProjectFundingItemForm.test.tsx
  app/src/features/projects/components/ProjectIUCNForm.test.tsx
  app/src/features/projects/components/ProjectIUCNForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectObjectivesForm.tsx
  app/src/features/projects/components/ProjectPartnershipsForm.tsx
  app/src/features/projects/components/ProjectPermitForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectFundingItemForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectIUCNForm.test.tsx.snap
  app/src/utils/customValidation.ts
Labels: BioHubBC, Task, enhancement, frontend

#259 API tests unlocked and permit/create project flow fixes
  api/package-lock.json
  api/package.json
  api/src/models/permit-no-sampling.test.ts
  api/src/models/permit-no-sampling.ts
  api/src/paths/permit-no-sampling.ts
  api/src/queries/permit-no-sampling/permit-no-sampling-queries.test.ts
  api/src/queries/permit-no-sampling/permit-no-sampling-queries.ts
  api/src/security/auth-utils.test.ts
  api/src/security/auth-utils.ts
  app/src/features/projects/CreateProjectPage.tsx
Labels: enhancement, technical debt

#261 Get self.ts to 100% coverage
  api/src/paths/user/self.test.ts
  api/src/paths/user/self.ts
  api/src/security/auth-utils.ts
Labels: not using any openshift resources, technical debt

#262 Get user.ts to 100% coverage
  api/src/paths/user.test.ts
  api/src/paths/user.ts
  api/src/paths/user/self.test.ts
Labels: technical debt

#265 Get codes.ts from 0-100 coverage and also permit-no-sampling coverage to 76%
  api/src/paths/codes.test.ts
  api/src/paths/codes.ts
  api/src/paths/permit-no-sampling.test.ts
  api/src/paths/permit-no-sampling.ts
  api/src/utils/code-utils.ts
Labels: not using any openshift resources, technical debt

#267 Implement the project metadata description text in the UI
  api/src/constants/codes.ts
  api/src/models/project-create.test.ts
  api/src/models/project-create.ts
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/codes.test.ts
  api/src/paths/codes.ts
  api/src/paths/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/paths/projects.ts
  api/src/queries/codes/code-queries.test.ts
  api/src/queries/codes/code-queries.ts
  api/src/queries/project/project-create-queries.test.ts
  api/src/queries/project/project-create-queries.ts
  api/src/queries/project/project-delete-queries.test.ts
  api/src/queries/project/project-delete-queries.ts
  api/src/queries/project/project-view-queries.ts
  api/src/queries/project/project-view-update-queries.test.ts
  api/src/queries/project/project-view-update-queries.ts
  api/src/utils/code-utils.ts
  app/src/features/projects/CreateProjectPage.test.tsx
  app/src/features/projects/CreateProjectPage.tsx
  app/src/features/projects/__snapshots__/CreateProjectPage.test.tsx.snap
  app/src/features/projects/components/ProjectDetailsForm.test.tsx
  app/src/features/projects/components/ProjectDetailsForm.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/components/ProjectPartnershipsForm.tsx
  app/src/features/projects/components/__snapshots__/ProjectDetailsForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectLocationForm.test.tsx.snap
  app/src/features/projects/components/__snapshots__/ProjectPartnershipsForm.test.tsx.snap
  app/src/features/projects/list/ProjectsListPage.test.tsx
  app/src/features/projects/list/ProjectsListPage.tsx
  app/src/features/projects/list/__snapshots__/ProjectsListPage.test.tsx.snap
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/projects/view/__snapshots__/ProjectDetails.test.tsx.snap
  app/src/features/projects/view/components/GeneralInformation.test.tsx
  app/src/features/projects/view/components/GeneralInformation.tsx
  app/src/features/projects/view/components/IUCNClassification.test.tsx
  app/src/features/projects/view/components/IUCNClassification.tsx
  app/src/features/projects/view/components/Partnerships.tsx
  app/src/features/projects/view/components/__snapshots__/GeneralInformation.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/IUCNClassification.test.tsx.snap
  app/src/features/projects/view/components/__snapshots__/Partnerships.test.tsx.snap
  app/src/interfaces/useCodesApi.interface.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/code-helpers.ts
  app/src/test-helpers/project-helpers.ts
  app/src/utils/ProjectStepComponents.test.tsx
  app/src/utils/ProjectStepComponents.tsx
  app/src/utils/__snapshots__/ProjectStepComponents.test.tsx.snap
Labels: BioHubBC, Task, enhancement, forms, frontend
