Repository bcgov/biohubbc, pull requests merged in 2023-10, with the labels that each got.

#1105 Telemetry UI Updates
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments.ts
  app/src/components/buttons/HelpButtonTooltip.tsx
  app/src/components/fields/CbSelectFieldWrapper.tsx
  app/src/components/fields/TelemetrySelectField.tsx
  app/src/constants/i18n.ts
  app/src/features/surveys/view/SurveyAnimals.test.tsx
  app/src/features/surveys/view/SurveyAnimals.tsx
  app/src/features/surveys/view/survey-animals/IndividualAnimalForm.tsx
  app/src/features/surveys/view/survey-animals/SurveyAnimalsTable.tsx
  app/src/features/surveys/view/survey-animals/SurveyAnimalsTableActions.tsx
  app/src/features/surveys/view/survey-animals/TelemetryDeviceForm.tsx
  app/src/features/surveys/view/survey-animals/TelemetryFileUpload.tsx
  app/src/features/surveys/view/survey-animals/device.ts
  app/src/features/surveys/view/survey-animals/form-sections/FormSectionWrapper.tsx
  app/src/features/surveys/view/survey-animals/form-sections/GeneralAnimalForm.tsx
  env_config/env.docker
Labels: Early Feedback Welcome

#1128 SIMSBIOHUB-296/313: Import Observations
  Makefile
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/get.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/get.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/upload.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/upload.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/{submissionId}/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/{submissionId}/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/{submissionId}/getSignedUrl.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/dwca/observations/submission/{submissionId}/getSignedUrl.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/process.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/process.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/upload.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/upload.ts
  api/src/repositories/observation-repository.test.ts
  api/src/repositories/observation-repository.ts
  api/src/services/observation-service.test.ts
  api/src/services/observation-service.ts
  api/src/utils/xlsx-utils/cell-utils.ts
  api/src/utils/xlsx-utils/worksheet-utils.ts
  app/src/components/dialog/ComponentDialog.tsx
  app/src/components/dialog/FileUploadDialog.tsx
  app/src/components/map/DatasetPopup.tsx
  app/src/components/map/FeaturePopup.tsx
  app/src/components/map/OccurrenceFeatureGroup.tsx
  app/src/components/map/components/BaseLayerControls.tsx
  app/src/components/publish/PublishSurveyDialog.tsx
  app/src/components/publish/SurveySubmissionAlertBar.tsx
  app/src/contexts/surveyContext.tsx
  app/src/features/surveys/observations/ObservationComponent.tsx
  app/src/features/surveys/observations/ObservationsTable.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.test.tsx
  app/src/features/surveys/view/components/SurveyProprietaryData.test.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/features/surveys/view/survey-observations/SurveyObservations.tsx
  app/src/features/surveys/view/survey-observations/components/ObservationFileCard.tsx
  app/src/features/surveys/view/survey-observations/components/ObservationMessagesCard.tsx
  app/src/features/surveys/view/survey-observations/components/ValidatingObservationsCard.tsx
  app/src/hooks/api/useDwcaApi.test.ts
  app/src/hooks/api/useDwcaApi.ts
  app/src/hooks/api/useObservationApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useDwcaApi.interface.ts
  app/src/interfaces/useObservationApi.interface.ts
  app/src/interfaces/usePublishApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
  app/src/utils/spatial-utils.tsx
  database/src/migrations/20231016000000_survey_observation_submission.ts
Labels: Staging

#1136 SIMSBIOHUB-177: Survey Study Area enhancements
  api/package-lock.json
  api/src/models/survey-create.test.ts
  api/src/models/survey-create.ts
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/repositories/administrative-activity-repository.ts
  api/src/repositories/draft-repository.ts
  api/src/repositories/sample-location-repository.test.ts
  api/src/repositories/sample-method-repository.test.ts
  api/src/repositories/sample-period-repository.test.ts
  api/src/repositories/site-selection-strategy-repository.test.ts
  api/src/repositories/site-selection-strategy-repository.ts
  api/src/repositories/survey-location-repository.test.ts
  api/src/repositories/survey-location-repository.ts
  api/src/services/survey-location-service.test.ts
  api/src/services/survey-location-service.ts
  api/src/services/survey-service.test.ts
  api/src/services/survey-service.ts
  api/src/zod-schema/json.ts
  app/package-lock.json
  app/package.json
  app/src/components/boundary/MapBoundary.tsx
  app/src/components/dialog/ComponentDialog.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/WFSFeaturePopup.tsx
  app/src/components/map/components/DrawControls.tsx
  app/src/components/map/components/DrawControls2.tsx
  app/src/components/map/components/ImportBoundaryDialog.tsx
  app/src/components/map/components/RegionSelector.tsx
  app/src/components/map/components/StaticLayers.tsx
  app/src/components/map/wfs-utils.tsx
  app/src/features/surveys/SurveyRouter.tsx
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/locations/StudyAreaMap.tsx
  app/src/features/surveys/components/locations/SurveyAreaList.tsx
  app/src/features/surveys/components/locations/SurveyAreaLocationForm.tsx
  app/src/features/surveys/components/locations/SurveyAreaMapControl.tsx
  app/src/features/surveys/components/locations/SurveyLocationPage.tsx
  app/src/features/surveys/edit/EditSurveyForm.tsx
  app/src/features/surveys/observations/sampling-sites/SamplingSiteList.tsx
  app/src/features/surveys/observations/sampling-sites/components/SamplingSiteMapControl.tsx
  app/src/features/surveys/observations/sampling-sites/edit/components/SamplingSiteEditMapControl.tsx
  app/src/features/surveys/view/components/SamplingMethods.tsx
  app/src/hooks/api/useAxios.test.tsx
  app/src/utils/mapBoundaryUploadHelpers.ts
Labels: Staging

#1142 SIMSBIOHUB-336/337
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/repositories/observation-repository.test.ts
  api/src/repositories/observation-repository.ts
  api/src/services/observation-service.test.ts
  api/src/services/observation-service.ts
  app/src/features/surveys/observations/ObservationComponent.tsx
  app/src/features/surveys/observations/sampling-sites/SamplingSiteList.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/interfaces/useObservationApi.interface.ts
Labels: Staging

#1144 SIMSBIOHUB 343 - Incorrect date overlap error in sampling methods
  app/src/features/surveys/components/EditSamplingMethod.tsx
  app/src/features/surveys/observations/sampling-sites/edit/SamplingSiteEditPage.tsx
Labels: Staging

#1143 SIMSBIOHUB-334/350/352
  app/src/contexts/observationsContext.tsx
  app/src/features/surveys/observations/ObservationComponent.tsx
  app/src/features/surveys/observations/ObservationsTable.tsx
Labels: Staging

#1153 SIMSBIOHUB-323: Remove Ecological Season
  api/src/models/survey-create.test.ts
  api/src/models/survey-create.ts
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view.test.ts
  api/src/models/survey-view.ts
  api/src/paths/codes.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update/get.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/repositories/code-repository.ts
  api/src/repositories/survey-repository.test.ts
  api/src/repositories/survey-repository.ts
  api/src/services/code-service.test.ts
  api/src/services/code-service.ts
  api/src/services/eml-service.test.ts
  api/src/services/eml-service.ts
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/components/PurposeAndMethodologyForm.tsx
  app/src/features/surveys/edit/EditSurveyForm.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.test.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.tsx
  app/src/interfaces/useCodesApi.interface.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/code-helpers.ts
  app/src/test-helpers/survey-helpers.ts
  database/src/migrations/20231027000000_deprecate_ecological_season.ts
  database/src/seeds/03_basic_project_survey_setup.ts
Labels: Staging, Ready For Review

#1146 SIMSBIOHUB 347/341 - Names from shapefiles
  api/src/repositories/sample-location-repository.ts
  api/src/services/sample-location-service.ts
  app/src/features/surveys/observations/sampling-sites/edit/components/SampleSiteEditForm.tsx
  app/src/features/surveys/observations/sampling-sites/edit/components/SampleSiteGeneralInformationForm.tsx
Labels: Staging

#1148 TechDebt: Map container refactor
  api/src/models/project-create.test.ts
  api/src/models/project-create.ts
  api/src/models/project-update.test.ts
  api/src/models/project-update.ts
  api/src/models/project-view.test.ts
  api/src/models/project-view.ts
  api/src/openapi/schemas/project.ts
  api/src/paths/project/{projectId}/update.ts
  api/src/paths/project/{projectId}/view.ts
  api/src/paths/search.test.ts
  api/src/paths/search.ts
  api/src/repositories/project-repository.test.ts
  api/src/repositories/project-repository.ts
  api/src/services/eml-service.test.ts
  api/src/services/eml-service.ts
  api/src/services/project-service.test.ts
  api/src/services/project-service.ts
  app/src/AppRouter.tsx
  app/src/components/boundary/MapBoundary.tsx
  app/src/components/map/MapContainer.test.tsx
  app/src/components/map/MapContainer.tsx
  app/src/components/map/WFSFeatureGroup.test.tsx
  app/src/components/map/components/Bounds.tsx
  app/src/components/map/components/DrawControls.tsx
  app/src/components/map/components/DrawControls2.tsx
  app/src/components/map/components/MapBaseCss.tsx
  app/src/constants/spatial.ts
  app/src/features/projects/components/ProjectLocationForm.test.tsx
  app/src/features/projects/components/ProjectLocationForm.tsx
  app/src/features/projects/create/CreateProjectForm.tsx
  app/src/features/projects/create/CreateProjectPage.test.tsx
  app/src/features/projects/edit/EditProjectForm.tsx
  app/src/features/projects/edit/EditProjectPage.tsx
  app/src/features/projects/view/ProjectPage.tsx
  app/src/features/projects/view/components/LocationBoundary.test.tsx
  app/src/features/projects/view/components/LocationBoundary.tsx
  app/src/features/search/SearchPage.test.tsx
  app/src/features/search/SearchPage.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/locations/StudyAreaMap.tsx
  app/src/features/surveys/components/locations/SurveyAreaMapControl.tsx
  app/src/features/surveys/observations/ObservationsMap.tsx
  app/src/features/surveys/observations/sampling-sites/components/SamplingSiteMapControl.tsx
  app/src/features/surveys/observations/sampling-sites/edit/components/SamplingSiteEditMapControl.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/features/surveys/view/survey-animals/TelemetryMap.tsx
  app/src/features/surveys/view/survey-animals/form-sections/LocationEntryForm.tsx
  app/src/hooks/api/useProjectApi.test.ts
  app/src/hooks/api/useSearchApi.test.ts
  app/src/hooks/api/useSearchApi.ts
  app/src/hooks/useBioHubApi.ts
  app/src/interfaces/useProjectApi.interface.ts
  app/src/test-helpers/project-helpers.ts
  app/src/utils/mapLayersHelpers.ts
  app/src/utils/mapUtils.ts
Labels: Staging, Ready For Review

#1149 SIMSBIOHUB-353/325: Survey form updates
  api/src/models/survey-create.test.ts
  api/src/models/survey-create.ts
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view.test.ts
  api/src/models/survey-view.ts
  api/src/paths/codes.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update/get.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/repositories/code-repository.ts
  api/src/repositories/survey-repository.test.ts
  api/src/repositories/survey-repository.ts
  api/src/repositories/validation-repository.test.ts
  api/src/repositories/validation-repository.ts
  api/src/services/code-service.test.ts
  api/src/services/code-service.ts
  api/src/services/eml-service.test.ts
  api/src/services/eml-service.ts
  api/src/services/validation-service.ts
  api/src/utils/xlsx-utils/worksheet-utils.ts
  app/src/features/surveys/CreateSurveyPage.tsx
  app/src/features/surveys/components/PurposeAndMethodologyForm.tsx
  app/src/features/surveys/components/SurveySiteSelectionForm.tsx
  app/src/features/surveys/edit/EditSurveyForm.tsx
  app/src/features/surveys/view/components/SurveyGeneralInformation.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.test.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.tsx
  app/src/interfaces/useCodesApi.interface.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/code-helpers.ts
  app/src/test-helpers/survey-helpers.ts
  database/src/migrations/20231030120000_depreciate_field_method.ts
  database/src/seeds/03_basic_project_survey_setup.ts
Labels: Staging, Ready For Review

#1147 SIMSBIOHUB-342: Delete Sampling Site
  api/src/paths/project/{projectId}/survey/{surveyId}/sample-site/{surveySampleSiteId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/sample-site/{surveySampleSiteId}/index.ts
  api/src/repositories/observation-repository.ts
  api/src/repositories/sample-period-repository.ts
  api/src/services/observation-service.ts
  api/src/services/sample-location-service.test.ts
  api/src/services/sample-location-service.ts
  api/src/services/sample-method-service.ts
  app/src/features/surveys/observations/sampling-sites/SamplingSiteList.tsx
  app/src/hooks/api/useSamplingSiteApi.ts
Labels: Staging
