Repository bcgov/biohubbc, pull requests merged in 2023-11, with the labels that each got.

#1152 SIMSBIOHUB 324 - Multiple Ecological Variables (Intended Outcomes)
  api/src/models/survey-create.test.ts
  api/src/models/survey-create.ts
  api/src/models/survey-update.test.ts
  api/src/models/survey-update.ts
  api/src/models/survey-view.test.ts
  api/src/models/survey-view.ts
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/list.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update/get.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/view.ts
  api/src/repositories/survey-repository.test.ts
  api/src/repositories/survey-repository.ts
  api/src/services/eml-service.ts
  api/src/services/survey-service.test.ts
  api/src/services/survey-service.ts
  app/src/components/fields/MultiAutocompleteField.tsx
  app/src/components/surveys/SurveysList.tsx
  app/src/features/surveys/components/PurposeAndMethodologyForm.tsx
  app/src/features/surveys/edit/EditSurveyForm.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.tsx
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
  database/src/migrations/20231027112600_intended_outcome_join_table.ts
  database/src/seeds/03_basic_project_survey_setup.ts
Labels: Staging, Ready For Review

#1156 SIMSBIOHUB 335: Tab Through Observation Edit
  app/src/components/data-grid/TextFieldDataGrid.tsx
  app/src/components/data-grid/TimePickerDataGrid.tsx
  app/src/components/data-grid/autocomplete/AsyncAutocompleteDataGridEditCell.tsx
  app/src/components/data-grid/autocomplete/AutocompleteDataGridEditCell.tsx
  app/src/components/data-grid/taxonomy/TaxonomyDataGridEditCell.tsx
  app/src/features/surveys/observations/ObservationsTable.tsx
Labels: Staging

#1158 SIMSBIOHUB-356: Update survey list endpoint to return a subset of survey fields
  api/src/paths/project/{projectId}/survey/index.test.ts
  api/src/paths/project/{projectId}/survey/index.ts
  api/src/paths/project/{projectId}/survey/list.test.ts
  api/src/paths/project/{projectId}/survey/list.ts
  api/src/repositories/survey-repository.ts
  api/src/services/survey-service.ts
  app/package-lock.json
  app/src/components/surveys/SurveysList.tsx
  app/src/contexts/projectContext.tsx
  app/src/features/projects/view/ProjectPage.test.tsx
  app/src/features/surveys/list/SurveysListPage.test.tsx
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/hooks/api/useSurveyApi.ts
  app/src/interfaces/useSurveyApi.interface.ts
  app/src/test-helpers/survey-helpers.ts
Labels: Staging, Ready For Review

#1157 SIMSBIOHUB-354-355: Study area and Sampling sites on observations map
  app/public/assets/icon/circle-medium.svg
  app/src/components/map/components/DrawControls.tsx
  app/src/components/map/components/MapBaseCss.tsx
  app/src/components/map/components/StaticLayers.tsx
  app/src/features/surveys/observations/ObservationsMap.tsx
  app/src/utils/mapBoundaryUploadHelpers.ts
  app/src/utils/mapUtils.ts
Labels: Staging, Ready For Review

#1154 SIMSBIOHUB-348: Delete single or many observation records
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/repositories/observation-repository.ts
  api/src/services/observation-service.ts
  app/package-lock.json
  app/src/components/dialog/YesNoDialog.tsx
  app/src/constants/i18n.ts
  app/src/contexts/observationsContext.tsx
  app/src/contexts/observationsTableContext.tsx
  app/src/features/surveys/observations/SurveyObservationPage.tsx
  app/src/features/surveys/observations/observations-table/ObservationComponent.tsx
  app/src/features/surveys/observations/observations-table/ObservationsTable.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.test.tsx
  app/src/features/surveys/view/components/SurveyPurposeAndMethodologyData.tsx
  app/src/hooks/api/useObservationApi.ts
  app/src/interfaces/useObservationApi.interface.ts
Labels: Staging, Ready For Review

#1161 SIMSBIOHUB-363: Import Survey Area Name and Description from Shapefile
  api/src/paths/project/{projectId}/survey/{surveyId}/sample-site/index.ts
  api/src/repositories/sample-location-repository.ts
  api/src/services/sample-location-service.test.ts
  api/src/services/sample-location-service.ts
  app/src/features/surveys/components/locations/SurveyAreaMapControl.tsx
  app/src/features/surveys/observations/sampling-sites/SamplingSitePage.tsx
  app/src/features/surveys/observations/sampling-sites/components/SamplingSiteMapControl.tsx
  app/src/utils/Utils.ts
Labels: Staging, Ready For Review

#1165 SIMSBIOHUB-371: Update Seed to Create Sampling Site and Observation Records
  database/src/seeds/03_basic_project_survey_setup.ts
Labels: Staging

#1160 SIMSBIOHUB-344: Tech debt: Observation Table Species display
  api/src/__mocks__/db.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/paths/taxonomy/species/list.ts
  api/src/paths/taxonomy/species/search.ts
  api/src/repositories/observation-repository.test.ts
  api/src/repositories/observation-repository.ts
  api/src/services/observation-service.test.ts
  api/src/services/observation-service.ts
  app/src/components/data-grid/taxonomy/TaxonomyDataGridEditCell.tsx
  app/src/components/data-grid/taxonomy/TaxonomyDataGridViewCell.tsx
  app/src/constants/i18n.ts
  app/src/contexts/observationsTableContext.tsx
  app/src/contexts/taxonomyContext.tsx
  app/src/features/surveys/observations/SurveyObservationPage.tsx
  app/src/features/surveys/observations/observations-table/ObservationComponent.tsx
  app/src/features/surveys/observations/observations-table/ObservationsTable.tsx
  app/src/features/surveys/observations/sampling-sites/SamplingSiteList.tsx
  app/src/features/surveys/view/SurveyPage.tsx
  app/src/hooks/api/useObservationApi.ts
  app/src/hooks/api/useTaxonomyApi.ts
Labels: Staging, Ready For Review

#1163 SIMSBIOHUB-361: Remove all study areas button
  api/src/paths/project/{projectId}/survey/create.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/update.ts
  app/src/components/map/components/ImportBoundaryDialog.tsx
  app/src/components/map/components/StaticLayers.tsx
  app/src/components/map/styles/MapBase.scss
  app/src/components/map/styles/MapBaseCss.tsx
  app/src/features/surveys/components/StudyAreaForm.test.tsx
  app/src/features/surveys/components/StudyAreaForm.tsx
  app/src/features/surveys/components/SurveySiteSelectionForm.tsx
  app/src/features/surveys/components/locations/SurveyAreaList.tsx
  app/src/features/surveys/components/locations/SurveyAreaMapControl.tsx
  app/src/features/surveys/edit/EditSurveyForm.tsx
  app/src/features/surveys/observations/ObservationsMap.tsx
  app/src/features/surveys/observations/sampling-sites/components/SamplingSiteMapControl.tsx
  app/src/features/surveys/observations/sampling-sites/edit/components/SamplingSiteEditMapControl.tsx
  app/src/features/surveys/view/components/SurveyStudyArea.tsx
  app/src/features/surveys/view/survey-animals/TelemetryMap.tsx
  app/src/features/surveys/view/survey-animals/form-sections/LocationEntryForm.tsx
  app/src/themes/appTheme.ts
Labels: Staging, Ready For Review

#1168 SIMSBIOHUB-332 - Observation Table Validation
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/services/observation-service.ts
  app/package-lock.json
  app/src/components/data-grid/CustomDataGrid.tsx
  app/src/components/data-grid/DataGridValidationAlert.tsx
  app/src/components/data-grid/DatePickerDataGrid.tsx
  app/src/components/data-grid/autocomplete/AsyncAutocompleteDataGridEditCell.tsx
  app/src/components/data-grid/autocomplete/AutocompleteDataGridEditCell.tsx
  app/src/components/data-grid/autocomplete/AutocompleteDataGridViewCell.tsx
  app/src/components/data-grid/conditional-autocomplete/ConditionalAutocompleteDataGridEditCell.tsx
  app/src/components/data-grid/conditional-autocomplete/ConditionalAutocompleteDataGridViewCell.tsx
  app/src/components/data-grid/taxonomy/TaxonomyDataGridEditCell.tsx
  app/src/components/data-grid/taxonomy/TaxonomyDataGridViewCell.tsx
  app/src/contexts/observationsTableContext.tsx
  app/src/contexts/taxonomyContext.tsx
  app/src/features/funding-sources/list/FundingSourcesTable.tsx
  app/src/features/surveys/observations/observations-table/ObservationComponent.tsx
  app/src/features/surveys/observations/observations-table/ObservationsTable.tsx
  app/src/features/surveys/view/survey-animals/SurveyAnimalsTable.tsx
Labels: Ready For Review
