Repository bcgov/biohubbc, pull requests merged in 2024-10, with the labels that each got.

#1382 SIMSBIOHUB-621: Handle Bad Deployment Data
  api/.docker/api/Dockerfile
  api/src/openapi/schemas/deployment.ts
  api/src/openapi/schemas/warning.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.ts
  api/src/services/import-services/critter/import-critters-strategy.ts
  api/src/utils/logger.test.ts
  api/src/utils/logger.ts
  app/src/contexts/telemetryDataContext.tsx
  app/src/contexts/telemetryTableContext.tsx
  app/src/features/surveys/observations/observations-table/grid-column-definitions/GridColumnDefinitions.tsx
  app/src/features/surveys/telemetry/TelemetryPage.tsx
  app/src/features/surveys/telemetry/deployments/edit/EditDeploymentPage.tsx
  app/src/features/surveys/telemetry/list/SurveyBadDeploymentListItem.tsx
  app/src/features/surveys/telemetry/list/SurveyDeploymentList.tsx
  app/src/features/surveys/telemetry/table/TelemetryTable.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetry.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetryPopup.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetryTable.tsx
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/hooks/api/useSurveyApi.ts
  app/src/interfaces/useBioHubApi.interface.ts
  database/.docker/db/Dockerfile
  env_config/env.docker
Labels: Early Feedback Welcome

#1379 More miscellaneous UI tweaks
  app/src/components/layout/Header.tsx
  app/src/components/species/components/SpeciesCard.tsx
  app/src/features/surveys/animals/animal-form/components/general-information/components/SelectedAnimalSpecies.tsx
  app/src/features/surveys/animals/list/AnimalListContainer.tsx
  app/src/features/surveys/animals/list/components/CritterListItem.tsx
  app/src/features/surveys/components/species/components/FocalSpeciesForm.tsx
  app/src/features/surveys/sampling-information/sites/SamplingSiteContainer.tsx
  app/src/features/surveys/sampling-information/techniques/create/CreateTechniquePage.tsx
  app/src/features/surveys/sampling-information/techniques/edit/EditTechniquePage.tsx
  app/src/features/surveys/sampling-information/techniques/table/SamplingTechniqueTable.tsx
  app/src/features/surveys/telemetry/deployments/create/CreateDeploymentPage.tsx
Labels: Ready For Review

#1385 Release Test to Prod
  api/.docker/api/Dockerfile
  api/src/openapi/schemas/deployment.ts
  api/src/openapi/schemas/warning.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.ts
  api/src/services/import-services/critter/import-critters-strategy.ts
  api/src/utils/logger.test.ts
  api/src/utils/logger.ts
  app/src/contexts/telemetryDataContext.tsx
  app/src/contexts/telemetryTableContext.tsx
  app/src/features/surveys/observations/observations-table/grid-column-definitions/GridColumnDefinitions.tsx
  app/src/features/surveys/telemetry/TelemetryPage.tsx
  app/src/features/surveys/telemetry/deployments/edit/EditDeploymentPage.tsx
  app/src/features/surveys/telemetry/list/SurveyBadDeploymentListItem.tsx
  app/src/features/surveys/telemetry/list/SurveyDeploymentList.tsx
  app/src/features/surveys/telemetry/table/TelemetryTable.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetry.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetryPopup.tsx
  app/src/features/surveys/view/survey-spatial/components/telemetry/SurveySpatialTelemetryTable.tsx
  app/src/hooks/api/useSurveyApi.test.ts
  app/src/hooks/api/useSurveyApi.ts
  app/src/interfaces/useBioHubApi.interface.ts
  database/.docker/db/Dockerfile
  env_config/env.docker
Labels: Ready For Review

#1387 BugFix: Remove Duplicate Environment Columns in Observations Table
  api/src/repositories/observation-subcount-environment-repository.ts
Labels: Ready For Review

#1388 SIMSBIOHUB-606: Upload Capture Attachments
  api/src/constants/attachments.ts
  api/src/database-models/critter_capture_attachment.ts
  api/src/database-models/critter_mortality_attachment.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/attachments/{attachmentId}/getSignedUrl.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/captures/{critterbaseCaptureId}/attachments/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/captures/{critterbaseCaptureId}/attachments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/captures/{critterbaseCaptureId}/attachments/upload.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/captures/{critterbaseCaptureId}/attachments/upload.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/index.ts
  api/src/repositories/critter-attachment-repository.interface.ts
  api/src/repositories/critter-attachment-repository.test.ts
  api/src/repositories/critter-attachment-repository.ts
  api/src/services/attachment-service.ts
  api/src/services/critter-attachment-service.test.ts
  api/src/services/critter-attachment-service.ts
  api/src/utils/file-utils.test.ts
  api/src/utils/file-utils.ts
  api/src/utils/logger.ts
  app/src/components/attachments/AttachmentTableDropzone.tsx
  app/src/components/data-grid/GenericGridColumnDefinitions.tsx
  app/src/components/file-upload/FileUpload.tsx
  app/src/features/surveys/animals/profile/captures/AnimalCaptureContainer.tsx
  app/src/features/surveys/animals/profile/captures/capture-form/components/AnimalCaptureForm.tsx
  app/src/features/surveys/animals/profile/captures/capture-form/create/CreateCapturePage.tsx
  app/src/features/surveys/animals/profile/captures/capture-form/edit/EditCapturePage.tsx
  app/src/features/surveys/animals/profile/captures/components/AnimalCaptureCardContainer.tsx
  app/src/features/surveys/animals/profile/mortality/components/AnimalMortalityCardContainer.tsx
  app/src/features/surveys/animals/profile/mortality/mortality-form/edit/EditMortalityPage.tsx
  app/src/features/surveys/view/survey-animals/animal.ts
  app/src/hooks/api/useAnimalApi.ts
  app/src/hooks/useS3Download.tsx
  app/src/interfaces/useCritterApi.interface.ts
  database/src/migrations/20240905000000_capture_mortality_attachment_tables.ts
Labels: Ready For Review

#1377 Add Comments to Observation Subcount
  api/src/openapi/schemas/observation.ts
  api/src/paths/observation/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/index.ts
  api/src/repositories/observation-repository/observation-repository.ts
  api/src/repositories/observation-repository/utils.test.ts
  api/src/repositories/observation-repository/utils.ts
  api/src/repositories/subcount-repository.test.ts
  api/src/repositories/subcount-repository.ts
  api/src/services/observation-service.ts
  api/src/utils/xlsx-utils/column-aliases.ts
  app/src/components/data-grid/GenericGridColumnDefinitions.tsx
  app/src/contexts/observationsTableContext.tsx
  app/src/features/surveys/observations/observations-table/ObservationsTableContainer.tsx
  app/src/features/surveys/observations/observations-table/export-button/ExportHeadersButton.tsx
  app/src/features/surveys/observations/observations-table/grid-column-definitions/comment/ObservationSubcountCommentDialog.tsx
  app/src/hooks/api/useObservationApi.ts
  app/src/interfaces/useObservationApi.interface.ts
  database/src/migrations/20240925121500_subcount_comment.ts
Labels: Ready For Review

#1383 SIMSBIOHUB-622: Allow Duplicate Ecological Unit Categories in Surveys
  .github/workflows/cleanClosedPR.yml
  .github/workflows/cleanMergedPR.yml
  .github/workflows/deploy.yml
  .github/workflows/deployStatic.yml
  .github/workflows/toDraft.yml
  app/src/components/species/ecological-units/EcologicalUnitDualSelect.tsx
  app/src/components/species/ecological-units/EcologicalUnitsOptionSelect.tsx
  app/src/components/species/ecological-units/EcologicalUnitsSelect.tsx
  app/src/features/surveys/animals/animal-form/components/ecological-units/EcologicalUnitsForm.tsx
  app/src/features/surveys/components/species/SpeciesForm.tsx
  app/src/features/surveys/components/species/components/FocalSpeciesEcologicalUnitsForm.tsx
Labels: Ready For Review

#1398 SIMSBIOHUB-627 - Deployments
  api/src/database-models/critter.ts
  api/src/database-models/deployment.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.ts
  api/src/repositories/deployment-repository/deployment-repository.interface.ts
  api/src/repositories/deployment-repository/deployment-repository.test.ts
  api/src/repositories/deployment-repository/deployment-repository.ts
  api/src/services/deployment-services/deployment-service.ts
  api/tsconfig.json
  app/src/hooks/api/useSurveyApi.ts
  database/src/migrations/20241007000000_bctw_telemetry_tables.ts
  database/src/migrations/20241008000000_bctw_migration.ts
Labels: Ready For Review

#1402 SIMSBIOHUB-627: Rename Deployment Files
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.interface.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.test.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.ts
  api/src/services/telemetry-services/telemetry-deployment-service.ts
Labels: Ready For Review

#1396 Update Survey Job Lookup Options for Survey Participants
  database/src/migrations/20241012021000_survey_jobs.ts
  database/src/seeds/01_db_system_users.ts
  database/src/seeds/03_basic_project_survey_setup.ts
Labels: Ready For Review

#1386 SIMSBIOHUB-623: Add Site Name and Description When Creating New Sampling Site
  app/src/features/surveys/sampling-information/sites/create/form/SampleSiteCreateForm.tsx
  app/src/features/surveys/sampling-information/sites/create/form/SampleSiteGeneralInformationCreateForm.tsx
  app/src/features/surveys/sampling-information/sites/edit/form/SampleSiteEditForm.tsx
  app/src/features/surveys/sampling-information/sites/edit/form/SampleSiteGeneralInformationForm.tsx
Labels: Ready For Review

#1410 SIMSBIOHUB-627: Import Telemetry CSV
  api/src/database-models/deployment.ts
  api/src/database-models/device_make.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/{deploymentId}/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/telemetry/import.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.interface.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.ts
  api/src/services/import-services/telemetry/import-telemetry-strategy.test.ts
  api/src/services/import-services/telemetry/import-telemetry-strategy.ts
  api/src/services/import-services/utils/datetime.ts
  api/src/services/telemetry-service.ts
  api/src/services/telemetry-services/telemetry-deployment-service.ts
  api/src/services/telemetry-services/telemetry-utils.ts
  api/src/utils/xlsx-utils/worksheet-utils.ts
Labels: Ready For Review

#1412 SIMSBIOHUB-627: API Updates
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments2/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/devices/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/devices/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/telemetry/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/telemetry/index.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.test.ts
  api/src/repositories/telemetry-repositories/telemetry-deployment-repository.ts
  api/src/repositories/telemetry-repositories/telemetry-vendor-repository.ts
  api/src/services/telemetry-services/telemetry-deployment-service.ts
  api/src/services/telemetry-services/telemetry-vendor-service.test.ts
  api/src/services/telemetry-services/telemetry-vendor-service.ts
Labels: Ready For Review

#1415 SIMSBIOHUB-627: Deprecate 2
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments/{deploymentId}/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/deployments/{deploymentId}/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/telemetry.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/critters/{critterId}/telemetry.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/delete.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.test.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/telemetry/index.ts
  api/src/paths/telemetry/manual/delete.test.ts
  api/src/paths/telemetry/manual/delete.ts
  api/src/paths/telemetry/manual/deployments.test.ts
  api/src/paths/telemetry/manual/deployments.ts
  api/src/paths/telemetry/manual/index.test.ts
  api/src/paths/telemetry/manual/index.ts
  api/src/paths/telemetry/manual/process.ts
  api/src/repositories/deployment-repository.ts
  api/src/repositories/telemetry-repositories/telemetry-vendor-repository.interface.ts
  api/src/repositories/telemetry-repositories/telemetry-vendor-repository.ts
  api/src/services/deployment-service.ts
  api/src/services/telemetry-service.ts
  api/src/services/telemetry-services/telemetry-vendor-service.test.ts
  api/src/services/telemetry-services/telemetry-vendor-service.ts
Labels: Not Ready For Review

#1389 SIMSBIOHUB-619: Import Observations With Sampling Information
  api/src/constants/dates.ts
  api/src/models/project-survey-attachments.ts
  api/src/openapi/schemas/observation.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/deployments/{deploymentId}/index.ts
  api/src/paths/project/{projectId}/survey/{surveyId}/observations/process.ts
  api/src/repositories/observation-repository/observation-repository.ts
  api/src/services/import-services/capture/import-captures-strategy.test.ts
  api/src/services/import-services/marking/import-markings-strategy.test.ts
  api/src/services/import-services/measurement/import-measurements-strategy.test.ts
  api/src/services/import-services/utils/datetime.test.ts
  api/src/services/observation-service.ts
  api/src/services/telemetry-service.ts
  api/src/utils/media/xlsx/xlsx-utils.ts
  api/src/utils/xlsx-utils/cell-utils.ts
  api/src/utils/xlsx-utils/column-aliases.ts
  api/src/utils/xlsx-utils/worksheet-utils.test.ts
  api/src/utils/xlsx-utils/worksheet-utils.ts
  app/src/contexts/observationsTableContext.tsx
  app/src/interfaces/useObservationApi.interface.ts
  database/src/migrations/20241023115300_observation_contraints.ts
Labels: Ready For Review
